### ISSUE TITLE
failed to compile, source file ... not found

### ISSUE THREAD

**Issue by anurat** [pug-php/ci-pug-engine#10]
Hello,

I have developed a CI4 app on a macbook and can run ci pug with no problem.
However when I deploy the app on ubuntu 22.04, PHP 8.1, Code igniter 4.2 I got this error.

```
Phug\CompilerException
Failed to compile: Source file /var/www/html/earth-en/app/views/pages/homepage/index.jade not found
Paths:
Extensions: , .pug, .jade
Line: 0
Offset: 0

```
And the controller calls `$this->view('pages/homepage', $this->data);` with a pug file at `app/Views/pages/homepage.pug`

After I added `$this->disallowJadeFile();` the error becomes

`Failed to compile: Source file /var/www/html/earth-en/app/views/pages/homepage/index.pug not found
`

Looking at view auto selection, when no view is provided it will look for `pages/homepage/index.pug` first and then `pages/homepage.pug`, I wonder there is a problem with it that makes it stop looking for `pages/homepage.pug` after `index.pug` is not found.

I also wonder why it works perfectly on my macbook but not on ubuntu.

Best Regards,

**Comment by anurat** [comment]
I think I found the problems.

CI3 has a lowercase `views` folder but CI4 has an uppercase `Views` folder.
When I rename `Views` folder to `views`, the pug files now can be found on ubuntu.

However, would you consider update the package so that it supports both CI3 and CI4?
Thank you for your work.

**Comment by kylekatarnls** [comment]
Hello, thanks for the inspection. Can you try to install `composer require ci-pug/ci-pug:dev-ci-4-view-path` and see if it uses the correct path?

**Comment by anurat** [comment]
Looks good now! Thank you so much!
