### ISSUE TITLE
ci-pug cannot use Pug\Pug

### ISSUE THREAD

**Issue by anurat** [pug-php/ci-pug-engine#3]
Hi @kylekatarnls ,

First of all, thanks for answering my issue in the other project (pug-php/ci-pug).
I was supposed to post an issue here but I opened too many windows and got confused. I did install ci-pug/ci-pug and should be able to follow the instructions on Readme page, but I got the following error.

I use PHP 7 and Code Igniter 3.1.8
I followed the instruction on Readme,
installed ci-pug via composer, the installation was successful,
set `$config['composer_autoload']` to `true`

On my controller I tried the following.

```php
class Welcome extends CI_Controller {
	use Pug;

	public function pug() {
		$this->view( 'pug_template' );
	}
}
```

But I got an error `Welcome cannot use Pug\Pug - it is not a trait`

What else do I need to do?
Thanks in advance,

**Comment by kylekatarnls** [comment]
OK, I better understand. In fact, you or your IDE added an `use Pug\Pug;` at the top of the file. so instead of using the `\Pug` trait, you're using the `\Pug\Pug` library. You can either remove it or explicitly write: `use \Pug;` inside your `Welcome` class.

**Comment by anurat** [comment]
Thanks for your reply, but no luck so far.
I use VS code and I'm sure it didn't add `use Pug\Pug;` anywhere.
I also tried both `use Pug;` and `use \Pug;` inside Welcome class but still got the same error.

**Comment by kylekatarnls** [comment]
Does your controller have a namespace? Can your put the controller file from the beginning? And could you try to put the following (for debug) just before `class Welcome extends CI_Controller {`:

```php
var_dump(class_exists('Pug\Pug'), trait_exists('Pug', true));
exit;
```

**Comment by anurat** [comment]
@kylekatarnls,

Thank you so much for your tips.
No, it doesn't have a namespace, no other code in the file.

I tried 
```php
var_dump(class_exists('Pug'), class_exists('Pug\Pug'), trait_exists('Pug', true));
```
and got
```php
bool(true) bool(true) bool(false) 
```
which showed that class Pug, Pug\Pug was loaded and trait Pug wasn't loaded.

I also tried to comment out in a file vendor/pug-php/pug/src/Pug.php
```php
class_alias(\Pug\Pug::class, 'Pug');
```
but I still got an error `Trait 'Pug' not found`

It seems to me that vendor/ci-pug/ci-pug/src/Pug.php wasn't loaded.
Is there anyway to make sure that it will get loaded?

my composer.json is minimal.
```javascript
{
    "require": {
        "ci-pug/ci-pug": "^1.3"
    }
}

```

**Comment by kylekatarnls** [comment]
I get it. Before there where no such alias Pug = Pug\Pug and the composer PSR autoload probably disallow trait and class with the same name and take the first found. I will have to rename the trait.

**Comment by anurat** [comment]
Thanks again for the quick reply!
I'd like to inform you also that I've tried to change the trait name to Pugs

```php
trait Pugs
{
    use Jade;
}

```

but it still didn't get loaded.

It seems changing filename to Pugs.php as well as changing trait name to Pugs does the trick.
Cheers!

**Comment by kylekatarnls** [comment]
Hi, please try to update to ci-pug 2.0.0 and rename the trait: `use CiPug;`

**Comment by anurat** [comment]
@kylekatarnls 
Thank you very much, Now it works without a problem.

**Comment by kylekatarnls** [comment]
Great!
